### ISSUE TITLE
use of boolean && with spawnflag

### ISSUE THREAD

**Issue by 4LT** [fabiolimamp/alkaline#38]
https://github.com/fabiolimamp/alkaline/blob/b47ad2f4f6cca8f4d10968d06f210066a1a274f1/monsters/monster_turret.qc#L178

I assume you meant to use & here with the spawnflag

**Comment by fabiolimamp** [comment]
Good old typo.
Thanks for the catch, corrected on 304c84aefe4698bfe248905c5798c27d0c1afebe
