### ISSUE TITLE
Math doesn't look right

### ISSUE THREAD

**Issue by 4LT** [fabiolimamp/alkaline#45]
https://github.com/fabiolimamp/alkaline/blob/46c5878895be981ac8cc74c34838eb12389be9be/math.qc#L38-L40

tan(θ) = sin(θ)/cos(θ), not cos(θ)/sin(θ)

**Comment by fabiolimamp** [comment]
Hm, true. That third component for the returned vector isn't actually used for anything tho - note that the `tan()` function below recalculates it on the fly based on sin and cos, and in there it's done correctly -, but still, it can be misleading.

You can blame Skelton on that, or whoever wrote it first haha those functions have been passed around for decades probably.
Anyway, thanks for the heads up.

Corrected on 1f2ed930f8671a768313da5b8d0a108158394112
